# home/modules/noctalia/noctalia-config.toml

[audio]
enable_overdrive = true

[bar.default]
# Чуть-чуть уменьшаем плотность фона для более мягкого размытия
background_opacity = 0.65
border = "primary"
center = [ "date", "clock", "caffeine" ]
end = [ "ram", "tray", "network", "bluetooth", "notifications", "volume", "brightness", "battery", "session" ]

# Отодвигаем панель от края экрана, делая её парящим "островком" (как в iOS/macOS)
margin_edge = 12
margin_ends = 180
panel_overlap = 0
start = [ "launcher", "wallpaper", "workspaces", "media", "audio_visualizer" ]
widget_spacing = 14 # Немного больше воздуха между виджетами

[battery]
warning_threshold = 20

    [battery.device."/org/freedesktop/UPower/devices/headset_dev_98_34_8C_F6_6A_1D"]
    warning_threshold = 20

[control_center]
sidebar = "full"
sidebar_section = "full"

    [control_center.calendar]
    show_events_card = false

[desktop_widgets]
enabled = true
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
pre_action_fade_seconds = 5

[location]
address = "Russia, Yaroslavl"
auto_locate = false
latitude = 63.5651
longitude = 53.6874

[lockscreen]
# Увеличиваем интенсивность размытия экрана блокировки для максимальной мягкости заднего плана
blur_intensity = 0.65
blurred_desktop = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004",
    "lockscreen-widget-0000000000000005"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 1480.0
    cy = 786.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.75 # Делаем форму логина нежнее
        background_radius = 18.0   # Закругляем под стиль Niri (18px)
        center_password_text = false
        input_opacity = 1.0
        input_radius = 8.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 240.0
    box_width = 464.0
    cx = 392.0
    cy = 136.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background_opacity = 0.0
        center_text = true
        clock_style = "digital"
        format = "{:%H:%M:%S}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 288.0
    box_width = 400.0
    cx = 216.0
    cy = 888.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        stat = "cpu_usage"
        stat2 = "cpu_temp"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 80.0
    box_width = 224.0
    cx = 1480.0
    cy = 544.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "label"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        description = ""
        opacity = 1.0
        title = "utyara3"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 336.0
    box_width = 416.0
    cx = 720.0
    cy = 1000.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "weather"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 464.0
    box_width = 704.0
    cx = 416.0
    cy = 456.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "calendar"

[plugins]
enabled = []

[shell]
app_icon_color = "on_surface"
app_icon_colorize = true
lang = "en"
niri_overview_type_to_launch_enabled = true
screen_time_enabled = true
time_format = "{:%H:%M:%S}"

    [shell.launcher]
    categories = false

    [shell.panel]
    # ВКЛЮЧАЕМ НАПЫЛЕННОЕ МЯГКОЕ РАЗМЫТИЕ вместо glass
    transparency_mode = "transparent_blur"

    [shell.screenshot]
    directory = "/home/utyara3/Pictures/Screenshots"

[theme]
# Меняем контрастный Gruvbox на эталон пастельной эстетики Catppuccin
builtin = "Catppuccin"
community_palette = "ADW"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "faithful"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "kitty", "niri", "qt" ]
    community_ids = [ "zen-browser", "neovim", "obsidian", "vscode", "discord", "obs", "steam", "telegram", "yazi" ]

[wallpaper]
directory = "/home/utyara3/Pictures/Images/Wallpapers"

    [wallpaper.default]
    path = "/home/utyara3/Pictures/Images/Wallpapers/red_guy.png"

    [wallpaper.last]
    path = "/home/utyara3/Pictures/Images/Wallpapers/red_guy.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/utyara3/Pictures/Images/Wallpapers/red_guy.png"

[widget.battery]
enabled = true

[widget.cat]
type = "noctalia/bongocat:cat"

[widget.network]
show_label = false

